### ISSUE TITLE
Add internationalization via i18n

### ISSUE THREAD

**Issue by oskosk** [shovelapps/shovelapps-cms#1]
https://github.com/mashpie/i18n-node

**Comment by f3rnando** [comment]
* [mashpie/i18n-node](https://github.com/mashpie/i18n-node)
* [i18next/i18next-node](https://github.com/i18next/i18next-node)

**Comment by f3rnando** [comment]
Now using [mashpie/i18n-node](https://github.com/mashpie/i18n-node)

**Comment by f3rnando** [comment]
Usage in the jade templates:
h1 #{__('Hello')}
h1= __('Hello')

**Comment by oskosk** [comment]
oh yeahhhh
