### ISSUE TITLE
Don't send spammy invites for me to join your organization

### ISSUE THREAD

**Issue by stevengill** [shovelapps/shovelapps-cms#125]
Not cool to spam me and others. Shitty practice.

**Comment by shazron** [comment]
+1 no spam

**Comment by purplecabbage** [comment]
@nahuelcandia what are you doing?

**Comment by shazron** [comment]
Closing this issue without apologizing, is not cool.

**Comment by nahuelcandia** [comment]
Hey, sorry guys. We just removed the group.

**Comment by purplecabbage** [comment]
Thanks @nahuelcandia 
Good luck with your project!
