### ISSUE TITLE
CMS crashes when .sessions/session.json gets fully emptied after some error

### ISSUE THREAD

**Issue by f3rnando** [shovelapps/shovelapps-cms#40]
Couldn't reproduce.
In certain context, the session.json file gets fully emptied (instead of having "{}") then the CMS crashes when trying to parse it and wont start again. The inmediate solution is to put the brackets in the file. (/filestorage/.sessions/session.json)

**Comment by oskosk** [comment]
Solved by dropping dependency on the `express-session-json` module and incorporating in the CMS's codebase.
